{% set name = "bluez" %}
{% set version = "5.50" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://www.kernel.org/pub/linux/bluetooth/{{ name }}-{{ version }}.tar.xz
  sha256: 5ffcaae18bbb6155f1591be8c24898dc12f062075a40b538b745bfd477481911

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - autoconf
  host:
    - libical
    - glib
    - dbus
  run:
    - libical
    - glib
    - dbus

test:
  commands:
    - test -f "${PREFIX}/lib/libbluetooth.so"

about:
  home: http://www.bluez.org/
  license: GPL v2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Official Linux Bluetooth protocol stack'
  description: |
    BlueZ provides support for the core Bluetooth layers and protocols.
    It is flexible, efficient and uses a modular implementation.
  doc_url: http://www.bluez.org/qualification/
  dev_url: http://www.bluez.org/development/

extra:
  recipe-maintainers:
    - scopatz
