{% set name = "qterminal" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/lxqt/qterminal/releases/download/{{ version }}/qterminal-{{ version }}.tar.xz
  sha256: e018ece0bd38124a2879a6fbb76dd6b9d70ae2b231845650ad363eeca756fe31

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - cmake >=3.1.0
    - {{ cdt('mesa-libegl') }}
    - {{ cdt('mesa-libegl-devel') }}
  host:
    - lxqt-build-tools
    - qt >=5.2
    - freeglut
    #- mesa-libegl-cos6-x86_64
    #- mesa-libegl-devel-cos6-x86_64
    #- mesalib
    #- libglu
    #- xorg-libx11
    #- xorg-libxext
    #- xorg-glproto
  run:
    - qt >=5.2
    #- mesalib
    #- libglu

test:
  commands:
    - qterminal --help

about:
  home: http://lxqt.org
  license: GPLv2.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Lightweight Qt terminal emulator based on QTermWidget'
  doc_url: http://lxqt.org
  dev_url: https://github.com/lxqt/qterminal

extra:
  recipe-maintainers:
    - scopatz
